[package]
name = "png"
version = "0.15.0"
license = "MIT OR Apache-2.0"

description = "PNG decoding and encoding library in pure Rust"
categories = ["multimedia::images"]
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/image-rs/image-png.git"

edition = "2018"
exclude = [
    "tests/*",
    "/sgx/*",
]

[dependencies]
inflate = { git = "https://github.com/mesalock-linux/inflate-sgx" }
deflate = { git = "https://github.com/mesalock-linux/deflate-rs-sgx", branch = "dev", optional = true }
num-iter = { git = "https://github.com/mesalock-linux/num-iter-sgx" }
bitflags = "1.0"
crc32fast = { git = "https://github.com/mesalock-linux/rust-crc32fast-sgx" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[dev-dependencies]
getopts = "0.2.14"
term = "0.6.1"
glob = "0.3"
rand = "0.7.0"

[dev-dependencies.glium]
version = "0.22"
features = ["glutin"]
default-features = false

[features]
png-encoding = ["deflate"]
default = ["png-encoding", "mesalock_sgx"]
unstable = []
benchmarks = []
mesalock_sgx = ["sgx_tstd"]
